#!/bin/bash

dataset_dir=${1:-/nas/common_data/imagenet_100cls}
[[ ! -d $dataset_dir ]] && echo "Dataset dir ${dataset_dir} not found!" && exit 1

/usr/bin/env python3 -m torch.distributed.launch \
        --nproc_per_node 1 \
        --master_port 12345 \
        main.py \
        --cfg configs/swin/swin_tiny_patch4_window7_224.yaml \
        --fused_window_process \
        --batch-size 512 \
        --data-path $dataset_dir
